### ISSUE TITLE
Auto-size nodes to content

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#106]
Let's have an option under File > Details... to auto-size nodes to content. To do this:
- Rename File > Details... to File > Properties...
- Rename "Pathway Details" title in this dialog to "Pathway Properties"
- Rename "Details..." under Network on the side bar to "Properties..."
- Add a checkbox as the last item in the dialog (now titled "Pathway Properties") with text "Auto-Size Nodes To Content", which is true by default.

When the option is enabled:
- When the node label is empty, use the default node size (as it is now).
- When the node label changes to something non-empty, resize the node (both width and height) to include label.
- If there is experiment data and at least one of them is currently viewable, then take the colored boxes under the label into account when calculating size.
- Do not enable resize handles (related extension has options to do this).

**Comment by ugurdogrusoz** [comment]
In line with our earlier discussion, let's simplify this new feature as follows. Instead of an option to satisfy when checked with every related operation (resize of the node, change in label or experiment data shown), implement a menu option "Resize Nodes To Content" under Edit menu (right before Undo/Redo). This will look at current node content (label and experiment data shown) and current node size and if needed, resize the node to exact fit to the contents.

**Comment by ugurdogrusoz** [comment]
Let's also leave some more padding around labels/experiment data, not fit so tightly.

**Comment by leonarddrv** [comment]
I cannot reproduce the bug where different collaborators see the nodes placed in different positions when "Resize nodes to content" option is clicked.

**Comment by ugurdogrusoz** [comment]
- User1 opens HIPPO in collaborative mode, loads mutation data for the first study in the list, and shares it with User2
- User2 loads the shared document and performs layout using the root context menu
Notice how 2 member RAS family is laid out differently on User1's screen (something is incorrectly laid out in User1 each time you try! the second time I tried it was the 4 member RAS family)
