### ISSUE TITLE
Tooltips for node and interaction tools

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#118]
For each node provide a tooltip as follows (multiple lines):

Click on this and drag to the
location on drawing canvas and
release!

For each interaction:

Click to activate; then, start the
interaction from the little circle
on the source node!

**Comment by leonarddrv** [comment]
I changed the display of interaction tooltips to 3 lines because previously left part of tooltip wasn't visible.

**Comment by ugurdogrusoz** [comment]
Let's please change the node tooltips to 3 lines as updated in the original description.
Also, let increase the delay (for tooltips). Assuming it's currently 1 second, increment it to 2.5 seconds.
