### ISSUE TITLE
Problems with Remove Selected From Parent

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#124]
Firstly we should rename this as "Remove This From Parent" as the current name is incorrect.
Also, when a node is removed from its parent, its size changes! To reproduce:
- Create 1 simple node s, and one compound node c
- Selected s and on c perform "Add Selected Into This"
- Now on s, perform "Remove This From Parent"
Notice how s becomes wider! (and c becomes narrower?)

**Comment by leonarddrv** [comment]
I renamed the option but the functionality of it also includes removing all selected nodes from their parents. Should I change it too?

**Comment by ugurdogrusoz** [comment]
I noticed that as well (I hadn't realized). Let's discuss tomorrow.

**Comment by leonarddrv** [comment]
Regarding the exclusion of simple nodes in Remove Selected From This, I couldn't omit it before clicking since we don't have Class property of nodes (like in Newt)

**Comment by ugurdogrusoz** [comment]
OK, so our menus won't be as sensitive :)
That's OK.
