### ISSUE TITLE
Add help information about the queries used to retrieve CBioPortal information

### ISSUE THREAD

**Issue by cannin** [iVis-at-Bilkent/pathway-mapper#129]
Below should be the queries used

* Copy Number: Amplifications and deep deletions are used in the percentage calculation
* Expression: mRNA up and downregulation (z-score data used and samples with +/- 2) are used in the percentage calculation
* Mutation: Mutations (any mutations: deletions/insertions, missense with and without known significance) and fusions are used in the percentage calculation

**Comment by ugurdogrusoz** [comment]
@cannin thanks for the suggestion and the text to be used. I suggest we provide this in the query dialog:
  
![help-text-alteration-types](https://user-images.githubusercontent.com/3874988/36303418-23856f3c-131d-11e8-8a9c-7d76f9ceafe0.png)

Does that make sense?

**Comment by cannin** [comment]
Agreed a question mark tooltip is how it is done on CBioPortal.

**Comment by ugurdogrusoz** [comment]
@leonarddrv Can we please use this exact text with multi-lines:

Amplifications and deep deletions are used in the percentage calculation

mRNA up and down regulation (z-score data used and
samples with +/- 2) are used in the percentage calculation

Mutations (any mutations: deletions/insertions, missense with and without
known significance) and fusions are used in the percentage calculation

Also, can we change the style to be the reverse (black background and white text) like we used to have elsewhere?

**Comment by ugurdogrusoz** [comment]
Thanks Leonard, this is great. Just one thing for consistency. Can we please make the tooltip box corners rounded a bit (similar to node and edge inspector boxes)?
