### ISSUE TITLE
SVG export does not support bends

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#132]
When you save a map with bends for interactions, SVG export doesn't handle them (instead each interaction is drawn as a single line segment; i.e., no bends).

**Comment by leonarddrv** [comment]
This commit: fcba1f036e92b8b8311475a8d68fa08a1b0ff486 solves this issue.

**Comment by ugurdogrusoz** [comment]
I cannot confirm this; it's still not working, no bends.
