### ISSUE TITLE
Missing experiment data in collaborative mode

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#144]
- Load TCGA > PanCanAtlas > Cell Cycle
- Alterations > Load from cBioPortal > AML 2013 (third one from top, all three types)
- Only see one of them: 
![pathway 6](https://user-images.githubusercontent.com/3874988/43594067-f79a7406-9681-11e8-9075-dd5a475a00c5.png)
- Sometimes, afterwards, apparently nothing you do gets reflected to the server and other clients see a totally different, out-dated picture.
- Interestingly, a new client using the same ID might see the correct picture.

**Comment by ugurdogrusoz** [comment]
Operations for showing/hiding a data set done through Alteration % > View Settings isn't performed correctly.

**Comment by hasanbalci** [comment]
Similarly, Alteration % > Remove Data isn't working and gives error in console.

**Comment by kaansancak** [comment]
@ugurdogrusoz @hasanbalci This should be fixed. Can you confirm?
