### ISSUE TITLE
Collaborative map geometry inconsistency

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#145]
Started a collaborative map: http://pathwaymapper-unstable.herokuapp.com/?id=409b81c1-a7dc-45f9-96af-8c88a467c8d0#
Loaded a template
Resized some nodes
Created some bends
In 3 windows I have 3 different geometry:
![pathway 7](https://user-images.githubusercontent.com/3874988/43595225-d40c272a-9684-11e8-984b-6e2ab050e743.png)
![pathway 8](https://user-images.githubusercontent.com/3874988/43595232-d87e3a82-9684-11e8-8041-fa09479791fe.png)
![pathway 9](https://user-images.githubusercontent.com/3874988/43595237-db9566fa-9684-11e8-8b7e-7eec8cc7b257.png)

**Comment by ahmetcandiroglu** [comment]
I tried to reproduce the bug but I could not. Is there a certain action to do (I tried node resize, move and create bend) or template that we have to use in order to reproduce this bug? @ugurdogrusoz

**Comment by ugurdogrusoz** [comment]
Looks like you have to try pretty hard. Might be a bug from before (not related to sharejs). I think it has to do with bends. Try creating, moving and deleting bends perhaps.

**Comment by kaansancak** [comment]
@ugurdogrusoz I also tried to reproduce the bug but could not. Can you check it again?

**Comment by ugurdogrusoz** [comment]
![collaborative-bend-issue](https://user-images.githubusercontent.com/3874988/46853474-dbf21080-ce06-11e8-8cc4-7b1e47b7869e.gif)

**Comment by kaansancak** [comment]
It should be fixed now! Can you confirm ? @ugurdogrusoz
