### ISSUE TITLE
Updating bend points fails on collaborative maps

### ISSUE THREAD

**Issue by kaansancak** [iVis-at-Bilkent/pathway-mapper#147]
- Open a collaborative map 
- Try to add bend poits
Syncronization between clients fails and vertices between nodes cannot be updated anymore. This bug appeared after updating edge bend editing to edge editing.

**Comment by ugurdogrusoz** [comment]
Same as #145?

**Comment by kaansancak** [comment]
Yes. It seems like they are same.
