### ISSUE TITLE
Edge reconnection handles (and bends) disappear after reconnection

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#148]
- Create two nodes with an edge between them
- Create a new node and reconnect one end of the edge to the new node
- Now select the edge to see no reconnection handles (and bends if any)

**Comment by kaansancak** [comment]
This bug might relate to #145 @ugurdogrusoz

**Comment by ahmetcandiroglu** [comment]
Fixed @ugurdogrusoz

**Comment by ugurdogrusoz** [comment]
This particular bug seems to be fixed, thanks! However #145 (collaborative) is still there.
