### ISSUE TITLE
Load from data

### ISSUE THREAD

**Issue by itsacurse** [iVis-at-Bilkent/pathway-mapper#155]
Hi,

I have a hard time to use the load from data in Alteration. Could you provide a sample (txt file) for it?

thank you!

**Comment by ugurdogrusoz** [comment]
@itsacurse Please refer to the [README in GitHub](https://github.com/iVis-at-Bilkent/pathway-mapper) (section titled Viewing Experiment Data).

**Comment by itsacurse** [comment]
Thank you. I have read it and followed the steps previously. I would like to import the mutation data, but it does not work. After loading the data, Data View Settings shows every gene and mutation rate in an individual checkbox instead of in one data set. Therefore, there is no number shown in the pathway.
When I make the txt file, is there anything I need to pay attention to. It seems that the tool does not recognize the txt file I created.
Thank you!

**Comment by ugurdogrusoz** [comment]
If you share your map and overlay data with us as .txt files, we might be able to help. You can email them to ivis@cs.bilkent.edu.tr if you don't want to include them here.
