### ISSUE TITLE
Tooltips not working

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#156]
On Heroku deployment, the tooltips aren't working. Neither the ones for the tools in the toolbar, nor the ones in the right panel for help, etc.

**Comment by ugurdogrusoz** [comment]
Can we also make the tooltip style consistent with other tabs please? I can see that at least the background colors aren't the same (black vs white).

**Comment by Rgtemze** [comment]
This fceadb6 commit fixes the issue that prevented tooltips from showing up.
