### ISSUE TITLE
About dialog not working

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#157]
On the Heroku deployment, nothing happens when you click on the About (i) icon.

**Comment by ugurdogrusoz** [comment]
Now missing the i-vis and mskcc logos

**Comment by Rgtemze** [comment]
This fceadb6 commit resolves the bug that prevented About button from functioning.

**Comment by ugurdogrusoz** [comment]
Can we also change the order of About and Edit pathway? About should be at the end.

**Comment by ugurdogrusoz** [comment]
Great! Can we add a bit more space before the i-Vis logo?
![image](https://user-images.githubusercontent.com/3874988/60967719-fd474500-a323-11e9-9f8f-b5473fe1c667.png)

**Comment by Rgtemze** [comment]
![Ekran Görüntüsü - 2019-07-10 15-44-31](https://user-images.githubusercontent.com/8372277/60970115-f0c5eb00-a329-11e9-95d5-a5f66e8bd5b7.png)
Theoretically both spaces are 15 px. Does it look fair?

**Comment by ugurdogrusoz** [comment]
Sure
