### ISSUE TITLE
Ranking table style problems

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#158]
![image](https://user-images.githubusercontent.com/3874988/60887382-ee498f80-a25c-11e9-938b-7e1caa97d576.png)

With the Heroke deployment, neither the titles nor the values in rows below nicely fit to the table (split into 2 lines).

**Comment by Rgtemze** [comment]
@ugurdogrusoz I feel that 2 and 3-digit scores (75.00, 100.00, 66.75) cause the overflow. should I try removing the digits that are right to the decimal point safely by rounding to the nearest integer.

**Comment by ugurdogrusoz** [comment]
If there is enough room for 1 digit after the decimal point, that'd be great.

**Comment by Rgtemze** [comment]
That way numbers greater than or equal to 100 would lead to the overflow unless I increase the width of the table.

**Comment by ugurdogrusoz** [comment]
How about decreasing the table cell margins?

**Comment by ugurdogrusoz** [comment]
Alternatively, if at least one of the scores is 3 digits, we could truncate to an integer.

**Comment by Rgtemze** [comment]
The problem turned out to be the following: cBioPortal stylesheets override our css which caused table cells to have left-right paddings of 10px which used to be 5px in our stylesheets. I will declare our padding amount as !important to overcome the problem

**Comment by Rgtemze** [comment]
![Ekran Görüntüsü - 2019-07-10 15-44-31](https://user-images.githubusercontent.com/8372277/60970020-bb210200-a329-11e9-9c9b-519186add650.png)
Theoretically both spaces are 15px. Does it seem fair?
