### ISSUE TITLE
Modify query bug

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#167]
From @inodb 
When I query TP53 in MSK-IMPACT and go to pathway mapper. When I click on Modify query the tab disappears and it is not possible to see which genes are in that pathway. Another minor issue: the modify query button becomes blank.

**Comment by ugurdogrusoz** [comment]
Looks like it's not only the PM tab that disappears. Could be a more general problem (not specific to PM)?

**Comment by Rgtemze** [comment]
71caa58 fixes blank button issue.
