### ISSUE TITLE
React version style issues

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#168]
[Old](http://pathwaymapper-unstable.herokuapp.com/) and [New](http://react-pathway-mapper.herokuapp.com/) PMs tested. Tests are performed on Win 10, Chrome latest version. Problems found in the new version:
- [x] 1. Pathway Properties dialog title and input fields are not aligned. Align the titles (e.g. "File Name:") to be left justified as before
- [x] 3. Search box is on a separate row (should be to the right of toolbar, aligned to the right as before)
- [x] 5. Compartment tool image/icon on the left panel is not as big (compared to others) as it used to be:
![image](https://user-images.githubusercontent.com/3874988/61378600-6859c400-a8ae-11e9-9fec-93f5e58a500d.png)
![image](https://user-images.githubusercontent.com/3874988/61378615-73145900-a8ae-11e9-8cd9-9baf764a2f8b.png)
- [x] 7. Tooltip background is darker than it used to be (it should be the same color as the background of the menu bar):
![image](https://user-images.githubusercontent.com/3874988/61378887-09e11580-a8af-11e9-9fde-3006f7db2f28.png)
- [x] 8. Tooltip text font size is bigger than it should be (it shouldn't be bigger than the font size in the menu)
- [x] 9. When an alteration type (e.g. "Gene Expression") is disabled (since it's not available), we should use a light gray so it's better understandable that the alteration type is disabled/not available
- [x] 10. For such messages can we use a more visible/striking style? As before green background and white font perhaps?
![image](https://user-images.githubusercontent.com/3874988/61379595-832d3800-a8b0-11e9-938d-066510e1047f.png)
- [x] 11. In genomic data visibility settings, let's add a title as before "Data Set(s) to Show". Let's also change the color of the style on mouse over (similar to what we did in cBioPortal mode). Also make sure to write "There is currently no data to show" when there is nothing to show.
![image](https://user-images.githubusercontent.com/3874988/61379868-08b0e800-a8b1-11e9-869a-fe56b3f54791.png)
- [x] 12. In Layout Settings dialog, some option names are not properly left aligned:
![image](https://user-images.githubusercontent.com/3874988/61380025-4dd51a00-a8b1-11e9-8a85-1d8e03c20d5c.png)
- [x] 13. Search box and icon don't have the same style as before: 1) Initial text: "Search Gene" -> "Search Genes..." 2) Text field and the icon together should have a single border, not separate ones.

**Comment by Rgtemze** [comment]
All except 2nd, 4th and 6th may be checked

**Comment by ugurdogrusoz** [comment]
1: "File Name" -> "File Name:"
12: the fonts used are different than others (e.g. Properties)
10: the color used here is different than the green we use all around (palette background for instance):
<img width="1280" alt="Screenshot 2019-07-21 at 09 45 14" src="https://user-images.githubusercontent.com/3874988/61587988-a3a10f00-ab9c-11e9-9ae8-20eb6c047ece.png">

**Comment by Rgtemze** [comment]
2nd, 4th and 6th items are moved to #181

**Comment by Rgtemze** [comment]
1, 10, 12, 13 may be checked.
Note for 12: Pathway Properties had a different font so I changed that.
