### ISSUE TITLE
Check for invalid genes broken

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#172]
Highlight > Identify Invalid Genes will not work (CORS policy problem)

**Comment by Rgtemze** [comment]
It seems to be unique to Heroku deployment as I could not reproduce it in my local deployment.

**Comment by Rgtemze** [comment]
I could not reproduce it on Heroku as well using Firefox / Ubuntu.

**Comment by ugurdogrusoz** [comment]
Can you try it on Windows / Chrome?
