### ISSUE TITLE
Add Selected Into This problems

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#174]
- [x] 1. Undo problem
  - Create two genes on empty canvas
  - Create a family
  - Select the two genes (using marquee selection since selecting one by one will revoke the node resize extension which is currently problematic)
  - Right click on Family and select "Add Selected Into This"
  - Operation is successful but Undo will not work as before
- [x] 2. Add Selected Into This will not work. In fact, if you refresh the page you'll notice that the change never made it to the server side. (In Collab. mode)

**Comment by Rgtemze** [comment]
When I downgrade cytoscape to 3.2.12, undo problem does not occur although problem with the collab. mode still persists.

**Comment by Rgtemze** [comment]
1 can be checked.

**Comment by Rgtemze** [comment]
2nd can be checked.
