### ISSUE TITLE
Some context menu times do nothing

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#175]
In the background, right click and choose
- [x] Undo
- [x] Redo
- [x] Load From cBioPortal
- [x] Delete Selected
Nothing seems to happen!

Similarly on node context menu
- [x] Remove Selected From Parent
will not work!

**Comment by Rgtemze** [comment]
I could not reproduce "Remove Selected From Parent" on Firefox 67.0.4 (64 bit) / Ubuntu 18

**Comment by ugurdogrusoz** [comment]
I confirm that Remove Selected From Parent is working properly, my mistake!
