### ISSUE TITLE
Undefined node(s) on load

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#177]
When you save a map, and load back, you see a node labeled "untitled".
![pathway (4)](https://user-images.githubusercontent.com/3874988/61442667-b7583580-a950-11e9-9344-dfe6b0643bd3.png)

If you save it back to disk, you see two nodes listed as "undefined": 
[ACC-2016-TP53-RB-pathway (1).txt](https://github.com/iVis-at-Bilkent/pathway-mapper/files/3405571/ACC-2016-TP53-RB-pathway.1.txt)

![pathway (5)](https://user-images.githubusercontent.com/3874988/61442737-dbb41200-a950-11e9-9e6c-e8c4f50da026.png)

**Comment by Rgtemze** [comment]
That undefined node seems to be the edge handle and this issue is somewhat related with #171.
