### ISSUE TITLE
Discrepancy in alteration values

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#178]
From Ino:
I would assume the % altered on the Oncoprint to be the same as the one in the pathwaymapper tab. Right now the percentages differ. Ideally both components should be getting the same number from the same store. The computation is complicated because it is possible that some samples weren't profiled for a particular gene.

**Comment by ugurdogrusoz** [comment]
For MDM2, 489/11356=0.04306 != %4.2 ?

![image](https://user-images.githubusercontent.com/3874988/61536775-219ad400-aa3e-11e9-8a74-23390cba9541.png)

![pathway (6)](https://user-images.githubusercontent.com/3874988/61536785-25c6f180-aa3e-11e9-940e-f45817080532.png)

**Comment by Rgtemze** [comment]
Could you try OncoPrint -> View -> Events per sample (instead of Events per patient)?

**Comment by ugurdogrusoz** [comment]
Then they match. Let's confirm with MSK folks.

**Comment by ugurdogrusoz** [comment]
Ino says the default is Events per patient. Let's go with that.
