### ISSUE TITLE
Misc improvements

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#179]
- [x] 1. No apply button for options, immediately apply upon change
- [x] 2. Use the same table component (lazy mobex, like enrichments/mutations tab) with search, download, pagination, etc. Show all pathways in table (10 per page)
- [x] 3. Rename table title Pathway rankings -> Pathways
- [x] 4. Move Pathways to top, and highlight the current pathway
- [x] 5. Show pathway name on the canvas (upper left)
- [x] 6. Pull data for other genes that are not queried (i.e. show alteration frequency for all genes; note that not all nodes in a pathway are genes)
- [x] 7. Differentiate query genes with thicker borders
- [x] 8. Add a new button using ~~[this icon](https://www.flaticon.com/free-icon/add_814159#term=add&page=7&position=82)~~[this icon](https://www.flaticon.com/free-icon/app_149941) titled "Add selected genes to query" to add selected genes to the query. Put this button after layout and before edit. Notice that not all selected objects will be genes.
- [x] 9. Add “Powered by PathwayMapper” below the diagram. Make sure the link on PM opens up in a separate, new tab
- [x] 10. If using OQL, other filters (UVS, germline), the tab should show the warning that the filters are applied
- [x] 11. Let's get rid of the border around these options I think it's unnecessary. If that's not enough to fit each option in one line including the question mark, let's decrease the font size to fit each in one line:
![image](https://user-images.githubusercontent.com/3874988/61547788-c1635c80-aa54-11e9-89aa-4ff02e42bb12.png)
- [x] 12. Let's add the icon for About box we removed but name it Help, and the content of the dialog is to contain some quick help & info: Provided by email.

**Comment by Rgtemze** [comment]
This commit d92f8f69765ef9e915803b2b451a79b2d397136d completes 1, 3, 5.

**Comment by Rgtemze** [comment]
7, 8 and 9 may be checked.

**Comment by ugurdogrusoz** [comment]
Let's use a different icon (as changed) for 8 please

**Comment by Rgtemze** [comment]
8 and 11 are complete.

**Comment by ugurdogrusoz** [comment]
Regarding 11, how different are font sizes for Match combobox and Alteration frequency checkbox text? They look very different. I suggest we make them the same,

**Comment by ugurdogrusoz** [comment]
Further improvements:
- [ ] 20. Table row margins are too big and the alignment of the content is not proper
- [ ] 21. Show more button becomes all white and stays that way for a while upon click
- [ ] 22. The space to the left of the tools and the space to the right of the pathway name on top of the canvas should be equal
- [ ] 23. "Reset" will overflow row and wrap, so let's shorten the button further so that all will fit in one row including "Reset" 
![image](https://user-images.githubusercontent.com/3874988/61880635-ed238e00-aefd-11e9-92dc-98d5570759f9.png)
- [ ] 24. Style of "Ranking options" looks odd as it is. Let's make it simpler like "Pathway name" style in the header of the table (black and bold):
![image](https://user-images.githubusercontent.com/3874988/61881104-bbf78d80-aefe-11e9-8c59-f84fef77438f.png)
- [ ] 25. Let's leave a little bit more space between the two Ranking options vertically

**Comment by Rgtemze** [comment]
20, 21, 22, 23, 24, 25 can be checked.

**Comment by Rgtemze** [comment]
12, 26, 27, 28 can be checked.

**Comment by ugurdogrusoz** [comment]
Regarding 12, can we format the list of icons and explanations so that they are like two separate columns and the text starts after the icons?

**Comment by Rgtemze** [comment]
12 and 29 are complete.

**Comment by ugurdogrusoz** [comment]
- [ ] 30. Can we not show the tooltips when we're already showing the entire content (pathway name and genes matched in the table)?
