### ISSUE TITLE
Misc improvements

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#183]
- [x] 1. In about dialog: 'PathwayMapper "2.0' -> 'PathwayMapper 2.0'
- [x] 2. There are two headers here redundantly. Let's remove the bottom one and change the top one as "Genomic Data Set(s) To Show"
![image](https://user-images.githubusercontent.com/3874988/61798990-f562c700-ae32-11e9-8dca-7da41d0de28e.png)
- [x] 3. Buttons listed under Data Set(s) To Show could be made larger (font size, that is)
- [x] 4. Let's get rid of the gray background in Interaction labels:
![image](https://user-images.githubusercontent.com/3874988/61937933-a46ce300-af98-11e9-805f-a5d5ca7c86cd.png)

**Comment by Rgtemze** [comment]
All may be checked.

**Comment by Rgtemze** [comment]
4 can be checked
