### ISSUE TITLE
Collaborative mode almost completely broken

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#184]
Collaborative mode seems almost completely broken. Renaming, move, new node/edge are not reflected to other clients at all.

**Comment by Rgtemze** [comment]
I could not reproduce it in Chrome / Windows.

**Comment by ugurdogrusoz** [comment]
Looks like if I restrict the sharing and operations to Windows + Chrome things are working fairly well. But if I use MacOS + Chrome, pretty much nothing works.

**Comment by Rgtemze** [comment]
2nd of #185 is moved to here. Problem is not specific to Mac OS. In Windows, sometimes clients might become indifferent to each together.

**Comment by ugurdogrusoz** [comment]
Specific issues with collaborative mode:
- [ ] some edge labels have gray background

**Comment by ugurdogrusoz** [comment]
Looks like the problem was with Heroku deployment. It seems to work nicely on our internal server.
