### ISSUE TITLE
Misc problems

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#185]
This collaborative mode test was done strictly using Windows + Chrome:
- [x] 1. When you add a PubMed ID (e.g. 12345) to an interaction, it gets saved as 0.
- [x] 3. Undo/Redo is not supported in collaborative mode, so they should be removed from the Edit menu and the toolbar.

**Comment by Rgtemze** [comment]
I could not reproduce 1 exactly in Ubuntu / Firefox. When I double clicked the interaction it showed me a 'default' PubMed ID '0' which is also the case in the unstable branch. Then, by typing PubMed ID and pressing enter, I could save it successfully.

**Comment by Rgtemze** [comment]
4th item (related to add selected into this) is moved to #174

**Comment by Rgtemze** [comment]
3 can be checked. It is also removed from context menu.

**Comment by ugurdogrusoz** [comment]
1 seems fixed now, maybe it was a cache issue

**Comment by Rgtemze** [comment]
2nd is moved to #184
