### ISSUE TITLE
Collaborative mode is not working

### ISSUE THREAD

**Issue by leiendeckerlu** [iVis-at-Bilkent/pathway-mapper#196]
Hi there,

after selecting collaborative mode on the start page and logging into my google account within the popup the spinning wheel starts spinning forever and never loads the actual editor.

Is that a known problem or exclusive to me?

Thanks,

Lukas

**Comment by ugurdogrusoz** [comment]
@leiendeckerlu Unfortunately Google deprecated Realtime API. Hence the collaborative mode is currently not working. But we are working on replacing this library and hope to release a new version in Sept. Sorry for the inconvenience.

**Comment by leiendeckerlu** [comment]
Ah well, that's a bummer. Maybe you could for the time being then remove the button to start the collaborative mode. I can imagine many people get confused by this.

Thanks,

Lukas

**Comment by ugurdogrusoz** [comment]
@leiendeckerlu We have now made version 2 of PathwayMapper publicly available. The collaborative mode along with many other [new features](https://github.com/iVis-at-Bilkent/pathway-mapper/milestone/3) are available.
