### ISSUE TITLE
Check license of each third party library for compatibility

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#201]
Could we please compile a list of 3rd party libraries and their licenses? E.g.:
- Backbone: MIT

**Comment by Rgtemze** [comment]
- net: none

- react-scripts-ts, shelljs: BSD-3-Clause

- ttf-loader, rimraf: ISC

- typescript, tslint-config-standard, typedoc, typescript, tslint: Apache-2.0

- coveralls: BSD-2-Clause

- @types/jquery, react-scripts, cytoscape-navigator, cytoscape-grid-guide, cytoscape-edgehandles, raw-loader, file-loader, mobx-react, @datastructures-js/max-heap, sharedb, autobind-decorator, cytoscape-undo-redo, @types/react, jquery-ui-dist, react-toastify, cytoscape, react-loader-spinner, react-scrollbar, konva, websocket-json-stream, ts-loader, react-bootstrap, cytoscape-node-resize, extract-text-webpack-plugin, express, @types/react-dom, ws, url-loader, react, react-tooltip, cytoscape-view-utilities, @types/cytoscape, underscore, @types/jest, file-saver, sharedb-mongo, cytoscape-qtip, jquery, source-map-loader, cytoscape-panzoom, cytoscape-cose-bilkent, bootstrap, @types/react-bootstrap, @commitlint/cli, prompt, replace-in-file, http-server, webpack-dev-server, colors, babel-loader, jest, jest-config, tslint-config-prettier, ts-node, babel, @commitlint/config-conventional, html-webpack-plugin, webpack, prettier, babel-preset-react, babel-core, webpack-cli, cz-conventional-changelog, commitizen, lodash.camelcase, @types/node, @types/jest, cross-env, lint-staged, babel-preset-env, travis-deploy-once, ts-jest, semantic-release, husky: MIT
