### ISSUE TITLE
Export as image not named appropriately

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#209]
"Export as" operations do not name files in line with map "Properties" (unlike "Export" which saves as text file)

**Comment by ugurdogrusoz** [comment]
Looks good. I tried a file with a weird name below. It doesn't load it. I suspect file read fails in the first line with pathway title.
[h lkhsh slh7___(&_(^_^ .txt.png.owl.txt](https://github.com/iVis-at-Bilkent/pathway-mapper/files/6108668/h.lkhsh.slh7___._._.txt.png.owl.txt)

**Comment by msalihaltun** [comment]
I could reproduce the problem with the filename yesterday but right now it seems to load fine. Could you test again?

**Comment by msalihaltun** [comment]
Now I am seeing it again. Fails without errors though.

**Comment by msalihaltun** [comment]
It is not related to filenames. We can't load file with the same name twice if the file importer value isn't reset in between. We ran into this one before in `cytoscape.js-expand-collapse` demos actually.
