### ISSUE TITLE
Multiple selection bug in Collaborative mode

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#216]
Try to select multiple nodes and edges as follows using the Shift key:
- Select a node
- Select an edge
- Select another node. The edge previously selected is now unselected. Only happens in Collaborative mode.

**Comment by msalihaltun** [comment]
I can't actually reproduce this bug in the daily build, what I found is that edges will get unselected on drag of multiple nodes/edges.

**Comment by ugurdogrusoz** [comment]
Unselecting single edge on drag is to avoid connection handles and anchor point residues. So thats expected. Let's investigate the problem you found. "the edge's endpoints stay rendered when another node is selected, if the edge is the only selected edge in the group."

**Comment by msalihaltun** [comment]
Since we decided https://github.com/iVis-at-Bilkent/cytoscape.js-edge-editing/issues/58 is by design and doesn't need a fix, I think we can close this now.

**Comment by ugurdogrusoz** [comment]
You're right, this no longer happens in the daily build.
