### ISSUE TITLE
Layout properties dialog improvements

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#217]
In Layout properties dialog:
- Many fields take non-numeric values resulting in NaN (should only take numeric values)
- We should decrease the width of the value fields so that labels aren't wrapped (e.g. 
"Compund Gravity\nRange" as opposed to "Compound Gravity Range" in a single line

**Comment by msalihaltun** [comment]
I just realized the values on the dialog can't be changed at all.

**Comment by ugurdogrusoz** [comment]
Nice but in some fields (e.g. node repulsion) one can actually type non-numeric values whereas in some others (e.g. nesting factor) you cannot! Can we make these consistent (all won't allow typing non-numeric)?

**Comment by ugurdogrusoz** [comment]
My bad I was testing it on the wrong tool (Newt) :)
