### ISSUE TITLE
Edit pathway will not work in portal mode

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#219]
- http://cbio-pm.herokuapp.com/results/pathways?Action=Submit&cancer_study_id=gbm_tcga_pub&cancer_study_list=gbm_tcga_pub&case_set_id=gbm_tcga_pub_sequenced&gene_list=PTEN&gene_set_choice=user-defined_list&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=gbm_tcga_pub_mutations&transpose_matrix=on
- Then "Edit pathway"

**Comment by Rgtemze** [comment]
This issue and https://github.com/iVis-at-Bilkent/pathway-mapper/issues/220 are related because for some genes alteration data may not be calculated thereby resulting in NaN value.
