### ISSUE TITLE
Nodes with alteration color black

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#220]
http://cbio-pm.herokuapp.com/results/pathways?Action=Submit&cancer_study_id=gbm_tcga_pub&cancer_study_list=gbm_tcga_pub&case_set_id=gbm_tcga_pub_sequenced&gene_list=PTEN&gene_set_choice=user-defined_list&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=gbm_tcga_pub_mutations&transpose_matrix=on

**Comment by Rgtemze** [comment]
As a solution, NaN values are replaced with 0.

**Comment by ugurdogrusoz** [comment]
We no longer have the black strip but let's make sure if we should display such nodes as "0%" or simply the same as genes with invalid symbols (label displayed at center).
