### ISSUE TITLE
Better module management

### ISSUE THREAD

**Issue by onursumer** [iVis-at-Bilkent/pathway-mapper#223]
Currently this repository actually contains 2 modules (a library and a standalone app), but there is only one `package.json` containing all the dependencies required for both of these modules.

Ideally there should be two separate modules (for example `react-pathway-mapper` and `pathway-mapper-standalone`) each having its own dependency management (`package.json`) and build directives (webpack config, rollup config, etc.). This can be achieved by adopting a monorepo strategy similar to https://github.com/cBioPortal/cbioportal-frontend.

**Comment by msalihaltun** [comment]
@onursumer I believe this is mostly completed on the [module management](https://github.com/iVis-at-Bilkent/pathway-mapper/tree/module-management) branch. 

One thing, as I was trying to put all imports in an index file in `pathway-mapper` package, I ran into some erros while importing it, specifically saying 'Can not use namespace as a type'. I tried to use cbioportal packages as an example to no avail, must be a small mistake but I can't find the exact cause really.

**Comment by msalihaltun** [comment]
I think this can be closed when `module-management` branch is merged into `unstable`.

**Comment by onursumer** [comment]
> @onursumer I believe this is mostly completed on the [module-management](https://github.com/iVis-at-Bilkent/pathway-mapper/tree/module-management) branch.
> 
> One thing, as I was trying to put all imports in an index file in `pathway-mapper` package, I ran into some erros while importing it, specifically saying 'Can not use namespace as a type'. I tried to use cbioportal packages as an example to no avail, must be a small mistake but I couldn't find the exact cause really.

@msalihaltun I think this is okay for now, we can fix it later.

**Comment by msalihaltun** [comment]
We can close this now.
