### ISSUE TITLE
Update outdated/deprecated libraries

### ISSUE THREAD

**Issue by onursumer** [iVis-at-Bilkent/pathway-mapper#224]
- [ ] Replace `underscore` with `lodash`.
- [ ] `extract-text-webpack-plugin` is deprecated, use `mini-css-extract-plugin` instead. See https://github.com/webpack-contrib/extract-text-webpack-plugin

**Comment by msalihaltun** [comment]
I made the updates for these libraies.

**Comment by onursumer** [comment]
Fixed by https://github.com/iVis-at-Bilkent/pathway-mapper/commit/ebf776f82e6b46e237f06bcd2de3c9afe0bc5a5b
