### ISSUE TITLE
Cleanup console.log calls

### ISSUE THREAD

**Issue by onursumer** [iVis-at-Bilkent/pathway-mapper#225]
There are way too many `console.log` calls in the library. Most of them are probably not needed leftover logs from previous debug efforts.

For the ones that are actually needed, it might be better to use a proper logging library instead of `console.log`.

**Comment by msalihaltun** [comment]
I cleaned up the log statements, only error cases remain.

For the logging library, I'm not sure how to proceed about it.

**Comment by onursumer** [comment]
For debugging purposes a log library like [winston](https://www.npmjs.com/package/winston) might be useful. But it's not a priority at this point. Cleaning up unwanted `console.log`s should be good enough.

**Comment by msalihaltun** [comment]
This should be done now.

**Comment by ugurdogrusoz** [comment]
@onursumer Please verify and close
