### ISSUE TITLE
Backward compatibility for existing collaborative mode maps

### ISSUE THREAD

**Issue by msalihaltun** [iVis-at-Bilkent/pathway-mapper#228]
The update to [unstable](https://github.com/iVis-at-Bilkent/pathway-mapper/tree/unstable) using `unstable` branches of all extensions, specifically [cytoscape.js-edge-editing](https://github.com/iVis-at-Bilkent/cytoscape.js-edge-editing/tree/unstable), is currently not backward-compatible for database records of collaborative files. 

Specifically, the data model stored for edges needed to change to include curve style information for compatibility with the 
`cytoscape.js-edge-editing` updates. A new field `edgeCurveStyle` with possible values `bezier`, `segments` and `unbundled-bezier` has been introduced for edges. The field name `bendPoint` has also been changed to `anchorPoints` as is the way the extension refers to these points now. Thus this model will not be able to sync anchor points between instances of the same map in collaborative mode that was created in the old version.

A couple of solutions I can see: We can add an exception to the code where if the edge was stored in the old model, use the new model to update it. This way all maps in storage could be updated to the new model over time. Another way would be to apply an update to all records in the database at once to change the field name and put style as `segments` whenever there are bend points and `bezier` whenever there are not. There will not be `unbundled-bezier` edges in the old version anyway.  

Note that this is likely to be a problem for the next release of PathwayMapper.

**Comment by ugurdogrusoz** [comment]
@msalihaltun Yes, I think we can add some conditional on read to check for old type of models.

**Comment by msalihaltun** [comment]
This was added when we updated the extensions [here](https://github.com/iVis-at-Bilkent/pathway-mapper/commit/964b7bcaf7b115789d4d9e3b56b0269eaa7e8f8e). We check whether a `bendPoint` field exists, update it as `anchorPoints` and use `edgeCurveStyle` parameter to determine whether the edge has bend or control points.
