### ISSUE TITLE
Saving maps as SVG can't handle some styles

### ISSUE THREAD

**Issue by msalihaltun** [iVis-at-Bilkent/pathway-mapper#232]
We currently have our own implementation of how to save a cytoscape graph as SVG with some utilities implemented for Cbioportal's results and patient views specifically.

But this implementation ignores (as so far discovered) curved edge styles and in some cases doesn't save them at all. This may apply to some other styles that were overlooked or were difficult to draw as SVG as well.

**Comment by msalihaltun** [comment]
Edge labels are also not drawn as text element on SVG.

**Comment by msalihaltun** [comment]
I was looking into [cytoscape-svg](https://github.com/kinimesi/cytoscape-svg), but it can't render nodes with alteration data. Also when used with `edge-text-rotation: autorotate` as we do, it can't render some colors as outlined [here](https://github.com/kinimesi/cytoscape-svg/issues/7).

**Comment by msalihaltun** [comment]
Should be able to draw control points on `Export as SVG` now. Please test for the changes so far @ugurdogrusoz.

Edge labels are kind of tricky because of rotation and width (starting point of the label). I will look into that as well.

Also a point worth noting is that since we draw nodes first, when edges are drawn later they go over nodes they were normally under (can see this happening with T arrow edges). We could solve this by drawing edges first and letting nodes be drawn over them. But in that case we will draw over edges that connect to nodes inside a compound node (which should go over the compound node and connect). Maybe we could come up with a layered approach that takes what is on top and should be visible into consideration.

**Comment by ugurdogrusoz** [comment]
I confirm that edge bend/control points are nicely rendered in SVG export now.

**Comment by msalihaltun** [comment]
Can also draw edge labels now.

**Comment by ugurdogrusoz** [comment]
Well done
