### ISSUE TITLE
StudyModal: Dropdown overflow problem and lack of search function

### ISSUE THREAD

**Issue by msalihaltun** [iVis-at-Bilkent/pathway-mapper#233]
Under `Alteration %` menu, `Load cBioPortal Data...` option reveals the `StudyModal`. The `Choose Study` dropdown, when opened, doesn't use any css `overflow` options, so the menu items cover a lot more than the page in height and vertical scrollbars appear. There are different ways we can go about this. 

The dropdown is also too wide because it tries to fit study names, which can be arbitrarily long. Maybe we should have a point past which we truncate study names with `...` and we show them in full (maybe in an animated way) on hover?

There is also no search bar that can be used to filter the studies, it is just sorted alphabetically.

I think, at least,
- The dropdown shouldn't overflow beyond the borders of the modal / a certain portion of the screen.
- There should be a search bar for studies integrated with the dropdown.

**Comment by ugurdogrusoz** [comment]
Agreed with both suggestions

**Comment by msalihaltun** [comment]
There is still an issue about the pop-up fetching which data is available from cbioportal and the interface not waiting for that. I'm not sure how to fix that yet. We could make the user wait until the fetch is completed, which may not be great UX, or prefetch all availability data. I'll think about it.

**Comment by msalihaltun** [comment]
Also there are some logs left in there, I will remove them later without making an additional commit about it.

**Comment by ugurdogrusoz** [comment]
Some UI issues:
- Marked spaces could be further reduced
- Border style (color and rounding) of the list could be the same as that of the search box

Bug:
- Close the dialog after searching for something (and limiting the content)
- On reopening even though there is no text in the Search box, the content is limited as before

**Comment by msalihaltun** [comment]
What do you think of the margins in the following @ugurdogrusoz?

![image](https://user-images.githubusercontent.com/26147738/110074677-a876fe80-7d92-11eb-8c03-ccedcfb8b58d.png)

With some studies selected:

![image](https://user-images.githubusercontent.com/26147738/110074696-b3ca2a00-7d92-11eb-84d9-105bef0557e6.png)

**Comment by ugurdogrusoz** [comment]
Great, thanks!

**Comment by ugurdogrusoz** [comment]
Good job!
