### ISSUE TITLE
Remove usages of cy.json()

### ISSUE THREAD

**Issue by msalihaltun** [iVis-at-Bilkent/pathway-mapper#235]
We currently use `cy.json()` in several places to serialize maps and access elements as JSON objects. It works correctly for now, but we can't always guarantee that maps will be serializable. There are equivalent functions in cytoscape core to access element data in JSON format.

**Comment by msalihaltun** [comment]
I removed 2 usages of `cy.json` and replaced them with equivalent functionality from the cytoscape core. There is still one usage remaining but it seems that one is not exactly matched by the core functionality.

**Comment by ugurdogrusoz** [comment]
@hasanbalci please verify and close if OK
