### ISSUE TITLE
Selected process nodes look unselected

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#238]
Since process nodes do not have any borders (0), they look unselected on selection since selection is done by changing node border color. Let's special case selection style to put a minimal border when selected. This border should go back to default zero when unselected.

**Comment by msalihaltun** [comment]
@ugurdogrusoz is this okay? 

![image](https://user-images.githubusercontent.com/26147738/108502254-93df3480-72c3-11eb-926e-7d26da73a546.png)

The border-width value for selected process above is 1.0, which is the same with unselected gene.

**Comment by ugurdogrusoz** [comment]
Yes looks good

**Comment by msalihaltun** [comment]
Also added some border width to highlighted processes for consistency.
