### ISSUE TITLE
Upgrade oncoprintjs to 5.0.0

### ISSUE THREAD

**Issue by adamabeshouse** [iVis-at-Bilkent/pathway-mapper#244]

**Comment by ugurdogrusoz** [comment]
Let's update and see if all is fine.

**Comment by msalihaltun** [comment]
https://github.com/iVis-at-Bilkent/pathway-mapper/pull/246 is now merged, you can point to pathway-mapper at https://github.com/iVis-at-Bilkent/pathway-mapper/commit/c629c3f35dd76e71215c6c6520f5eb7f97c4f6b0. Thanks @onursumer and @adamabeshouse.
