### ISSUE TITLE
Graphical notation improvements

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#250]
Currently complex and family notation are very similar (except the color of the rectangle borders). Similarly, the compartment is not very different than a gene either except its border width. Why not use more differentiating Cytoscape.js shapes? Barrel for compartment, cut rectangle for complexes for instance...

**Comment by ugurdogrusoz** [comment]
@YusufZiyaOzgul Please work with Hasan and propose a new notation for this.

**Comment by hasanbalci** [comment]
I prepared a candidate graphical notation. @YusufZiyaOzgul @ugurdogrusoz You can review it [here](https://docs.google.com/document/d/1YiJ_OS0MJWKFauHo1Aev69tlhRNrca9q3mcY5t6Rd3Y/edit?usp=sharing).

**Comment by ugurdogrusoz** [comment]
Thanks @hasanbalci looks good to me

**Comment by ugurdogrusoz** [comment]
I don't see the changes in the daily PM?

**Comment by ugurdogrusoz** [comment]
@YusufZiyaOzgul was this completed (in the unstable branch)?

**Comment by YusufZiyaOzgul** [comment]
@ugurdogrusoz this issue was solved. It can be closed.

**Comment by ugurdogrusoz** [comment]
@gorkemsolun Please change the images (.svg files) in the bar on the left (from where we drag nodes) to match the actual shapes:
![image](https://github.com/iVis-at-Bilkent/pathway-mapper/assets/3874988/c9d92713-cc40-4a73-8cc1-a7b394ff1884)
