### ISSUE TITLE
Switch to fcose layout style and use packing

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#251]
We shoud use fcose layout instead of cose-bilkent. We should also enable component packing from layout-utilities extension for both regular and incremental layout.

**Comment by ugurdogrusoz** [comment]
Something wrong with layout. To reproduce, load the following:
[KIRC-2013-RTK-RAS-PI(3)K-pathway.txt](https://github.com/iVis-at-Bilkent/pathway-mapper/files/6686576/KIRC-2013-RTK-RAS-PI.3.K-pathway.txt)

Resulting layout (see the node-node overlaps in the component on the right):
![KIRC-2013-RTK-RAS-PI(3)K-pathway](https://user-images.githubusercontent.com/3874988/122762092-9f5c5f80-d2a5-11eb-9375-b5cd2fbba385.png)

**Comment by hasanbalci** [comment]
@msalihaltun @ugurdogrusoz Probably, rebuild of PM will solve this issue, because I made a one last commit to layout-base for edges connected to ancestor.

**Comment by msalihaltun** [comment]
Updating lock file & rebuild solves it.
