### ISSUE TITLE
Inconsistent node sizing on load

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#253]
If you save a pathway and load it back some other time into a PM with a *different experiment data set*, we get inconsistently sized nodes (neither the same as the time they were saved, nor properly fitting the experiment data set at hand on load).

At the time of save:
![Screenshot 2021-06-21 110157](https://user-images.githubusercontent.com/3874988/122727974-4e864000-d280-11eb-80d5-de6018ed8869.png)

Upon load into another PM instance with different experiment data set:
![Screenshot 2021-06-21 110306](https://user-images.githubusercontent.com/3874988/122728004-580fa800-d280-11eb-9633-9f43d00c829a.png)

**Comment by msalihaltun** [comment]
With these changes we will stop overriding the stylesheet width value with "ideal width such that study information boxes can fit" whenever we have study data loaded. Instead we change data width properties of nodes to the ideal value only when studies are first being loaded. This way there won't be inconsistent resizing of nodes on import/export. Instead nodes can be resized to content from the menu whenever desired.

**Comment by ugurdogrusoz** [comment]
It's good that we do not resize them on load but now we lose the experiment data though. Even though there is data associated with certain genes, we don't show them on load:
![Screenshot 2021-06-22 173127](https://user-images.githubusercontent.com/3874988/122943431-b1aacc00-d37f-11eb-9bd2-25f009afd6d5.png)

**Comment by msalihaltun** [comment]
This is not actually about resizing nodes, it is related to [this](https://github.com/iVis-at-Bilkent/pathway-mapper/issues/114).
