### ISSUE TITLE
Collaborative mode problems

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#255]
- [x] 1. When you delete a bend or control point, this is not properly propagated to other clients. Remove all control/bend points operation is similarly problematic.
- [x] 2. Load a pathway, change its layout and then change the Color scheme. This somehow "resets" (anchor points are removed and layout goes back to the original) the graph.

**Comment by msalihaltun** [comment]
I believe the edge editing problems will be solved now.

**Comment by msalihaltun** [comment]
Point 2 actually happens outside of collaborative mode as well.
