### ISSUE TITLE
Layout Properties Editing

### ISSUE THREAD

**Issue by YusufZiyaOzgul** [iVis-at-Bilkent/pathway-mapper#259]
Changes on layout properties( ticking or unticking tickbox and changing the values of placeholders) do not reflect on the UI immediately.

https://user-images.githubusercontent.com/48672785/122932824-bb7c0180-d376-11eb-9756-686b9a405820.mp4

**Comment by ugurdogrusoz** [comment]
@YusufZiyaOzgul What platform (OS, browser) are you using? 
Can you try the same on our [daily build](http://ivis.cs.bilkent.edu.tr:3000/)?
Maybe your local deployment is problematic.

**Comment by YusufZiyaOzgul** [comment]
My local deployment is problematic, no issue.
