### ISSUE TITLE
Unexpected behavior on loading sample data

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/pathway-mapper#260]
- In collaborative mode, if "Load Sample Data" is clicked, seven unit of data are shown in Data Set(s):

![image](https://user-images.githubusercontent.com/22586369/122937468-aef9a800-d37a-11eb-9391-29b5c6eda913.png)

- Another unexpected behavior I observed (independent from mode) is that after loading some alteration data to a gene from cBioPortal, if "Load Sample Data" is clicked, more than six units of data are shown both in Data Set(s) and gene:

![image](https://user-images.githubusercontent.com/22586369/122938458-6f7f8b80-d37b-11eb-9784-a89542e83f08.png)
![image](https://user-images.githubusercontent.com/22586369/122938357-5bd42500-d37b-11eb-99b7-7e8b2ab61a0c.png)

**Comment by YusufZiyaOzgul** [comment]
There is another problem. 
For the collaborative mode, 
the screen of client 1 and client 2 are same at the beginning 
![2021-06-22 (3)](https://user-images.githubusercontent.com/48672785/122957732-e53f2380-d38a-11eb-9f6f-437cff35597f.png)

After client 1 selected the ovarian cancer( right one) on the screen, both of the ovarian cancers enabled.

![2021-06-22 (4)](https://user-images.githubusercontent.com/48672785/122958110-3c44f880-d38b-11eb-84f8-03500188afaa.png)

However, client 2 see that the ovarian cancer ( left one ) selected. 
![2021-06-22 (6)](https://user-images.githubusercontent.com/48672785/122958395-79a98600-d38b-11eb-87f2-c413704396c9.png)

**Comment by ugurdogrusoz** [comment]
@msalihaltun Should we force data set names to be unique to avoid some of these situations?

**Comment by msalihaltun** [comment]
I thought we actually checked for already existing data while loading, and we do, but we do that only for cBioPortal data. So multiple sample experiment data can actually be loaded. We use a different data flow to load experiment data compared to cBioPortal data. I'm gonna try to figure out a way to make sure:

1. We do not load multiple sample experiment data.
2. We do not exceed the limit of 6 data sets while loading sample data or data from file.

Ideally there would be a common path in code where data would flow through for cases like this.

**Comment by msalihaltun** [comment]
I disabled adding multiple sample data. Also the collaborative mode should properly respect the limit of 6 data sets shown.

**Comment by ugurdogrusoz** [comment]
Works well in general but I still see some edge case problems:
- Open a map
- Load a data set
- Load sample data
- Remove all data
- Load a data set
- Load sample data. We see 4 data sets in the dialog but the map renders more than 4 (a Resize to content will not help): 
![Screenshot 2021-06-24 115638](https://user-images.githubusercontent.com/3874988/123234452-a1136680-d4e3-11eb-9ad3-a4f94c2df24a.png)

**Comment by ugurdogrusoz** [comment]
Looks good to me. @hasanbalci @YusufZiyaOzgul please test and remove your assignment if OK.

**Comment by YusufZiyaOzgul** [comment]
There may be a another problem.

At the beginning I imported LUSC-2012-Notch-signaling-pathway and I fetched Acute Myeloid Leukemia (OHSU, Nature 2018)      and Thymoma (TCGA, PanCancer Atlas).
![2021-06-24 (5)](https://user-images.githubusercontent.com/48672785/123287453-675c5300-d517-11eb-8f7c-af427599c87a.png)
![2021-06-24 (6)](https://user-images.githubusercontent.com/48672785/123287498-6e836100-d517-11eb-9f2b-425a08da0cf8.png)

Then I imported LUAD-2014-Oxidative-stress-response-pathway using TCGA.
However, datas from the previous pathway still shown(activated) in data set but there is no information about them the new pathway.

![2021-06-24 (8)](https://user-images.githubusercontent.com/48672785/123288142-f5d0d480-d517-11eb-9169-000a129b471f.png)


I tried to deactivate and reactivate them on data set but still none of them shown on pathway.

Then, I fetched Cholangiocarcinoma (TCGA, PanCancer Atlas). 

![2021-06-24 (9)](https://user-images.githubusercontent.com/48672785/123288714-7bed1b00-d518-11eb-9b7c-5b6d4d899c1f.png)

After that,  data sets activated from previous pathway are shown on this pathway but data sets coming from previous pathway shown gray .  

![2021-06-24 (11)](https://user-images.githubusercontent.com/48672785/123289188-e605c000-d518-11eb-9a5e-537bfacb7de5.png)
![2021-06-24 (12)](https://user-images.githubusercontent.com/48672785/123289235-f158eb80-d518-11eb-9ab0-ab4889b3d536.png)

Finally, I removed all data sets and I re-fetched them and I got different result.
![2021-06-24 (13)](https://user-images.githubusercontent.com/48672785/123290478-fec2a580-d519-11eb-99ac-f7beda7ddde6.png)

**Comment by msalihaltun** [comment]
I believe this is intended, a known issue and related to https://github.com/iVis-at-Bilkent/pathway-mapper/issues/114.

**Comment by ugurdogrusoz** [comment]
Yes, this is a known issue. We only keep the data of a gene if that gene is currently in the map.
