### ISSUE TITLE
Chat for collaborative editing

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#269]
It'd be good to use a library (if possible) with an appropriate license to provide a chat facility for users working on a shared pathway in the collaborative mode. It's important that this window may be collapsed/hidden and even when it's in use it doesn't obstruct the map in the canvas (at least not significantly). The chat history of each specific shared pathway could be at least temporarily stored in the database (with a certain expiration period of say a week or 3 months as determined later on). If implemented this way, it might be a good idea to show previous chat content when the user closes their PM window comes back to the same shared pathway at a later time.

**Comment by YusufZiyaOzgul** [comment]
@ugurdogrusoz There is no issue related to this feature. It can be closed.
