### ISSUE TITLE
Too much information in the console

### ISSUE THREAD

**Issue by onursumer** [iVis-at-Bilkent/pathway-mapper#275]
Looks like Pathway Mapper prints a lot of information to the console in the cBioPortal production context. Ideally we should remove most of these `console.log` calls and only keep critical ones if any.

![image](https://user-images.githubusercontent.com/3604198/212191323-d0d61876-a252-44fe-92f6-15e97c9b4b75.png)

**Comment by ugurdogrusoz** [comment]
@gorkemsolun Please work with @YusufZiyaOzgul to understand and resolve this as a first issue

**Comment by gorkemsolun** [comment]
Looks like these logs have been removed, and this issue will be resolved when [this](https://github.com/cBioPortal/cbioportal-frontend/pull/4631) is merged.

**Comment by ugurdogrusoz** [comment]
@YusufZiyaOzgul please verify.
