### ISSUE TITLE
Location should be optional in export/import thru text files

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#40]
The location information {POSX,POSY} should be optional for nodes. If there is no such value in the file for that node, we can simply assume (0,0) by default for that node.

**Comment by ugurdogrusoz** [comment]
I exported the sample pathway and removed the locations ("x<tab>y<tab>") from each node line. It will read nodes at deafult location but won't recover interactions though (maybe the same bug as #39 ?)

**Comment by istemi-bahceci** [comment]
It should be OK now .
