### ISSUE TITLE
Complexes

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#44]
Add a new container type using rectangles with cut off corners as node shape (as in ChiSE) for complexes. Implementation should be pretty much the same as families since complexes can contain genes or other complexes. We should additionally allow complexes inside families and vice versa.

Notice that this will require modifications to the SVG support!

**Comment by ugurdogrusoz** [comment]
Since Cytoscape.js doesn't support such a shape for compounds, let's go with rounded rectangles (normal border width and more rounding around the corners compared to compartments).

**Comment by istemi-bahceci** [comment]
It seems that there is no option to specify rounding for the rounded-rectangle shapes in cytoscape.js.

**Comment by ugurdogrusoz** [comment]
Let's use a regular rectangle for complexes!
