### ISSUE TITLE
Load from file on server

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#45]
We'd like to be able to start PathwayMapper with a remote file on the server, for instance when a URL like this is used: http://tcga.patika.org/index.html?filename=pathway.txt. This should be redirected to http://tcga.patika.org/ but the model in pathway.txt should be loaded in Local mode. I suppose what we already use with the sample can be reused here.

**Comment by istemi-bahceci** [comment]
http://tcga.patika.org/index.html?filename=sample1.txt for example
