### ISSUE TITLE
Context sensitive menus dont sustain on Mac

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#46]
Use of context sensitive menus on Mac is problematic. When you right click on a node or in the root, the menu pops up but immediately closes as soon as you release, which makes use of the menu operations practically impossible.

**Comment by ugurdogrusoz** [comment]
Maybe there is an option in the extension that we use (https://github.com/cytoscape/cytoscape.js-cxtmenu) that can be changed to fix this? If not we can use our own extension: https://github.com/iVis-at-Bilkent/cytoscape.js-context-menus

**Comment by istemi-bahceci** [comment]
Context menus sustain now untill user performs another click.
