### ISSUE TITLE
Transfer problems

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#49]
Transferring a node into and out of a compound doesn't seem to work properly.

**Comment by istemi-bahceci** [comment]
Context menu plugin was causing such errors, I switched to using https://github.com/iVis-at-Bilkent/cytoscape.js-context-menus since it seems more stable !

**Comment by ugurdogrusoz** [comment]
Great. Can we improve the UI as follows: 1) decrease fonts size (to be the same as the ones in the menus for instance) 2) use rounded rectangles (instead of regular rectangles to be consistent with the menus)
