### ISSUE TITLE
Undo redo shortcuts on Mac

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#51]
If it's not much trouble, can we also map Cmd+z, y for Undo, Redo (as well as currently working Ctrl+z,y) on Mac?

**Comment by istemi-bahceci** [comment]
I do not have test environment for this issue, could you please check this ?

**Comment by ugurdogrusoz** [comment]
Cmd+z works fine but Cmd+y won't work for redo.

**Comment by ugurdogrusoz** [comment]
Sorry my bad. It does work fine. It just happens to do something else as well (load history).
