### ISSUE TITLE
TCGA pathways in Network menu

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#57]
Make TCGA pathways provided by Konnor available under the Network menu (instead of the Sample pathway; no longer need that) as discussed in emails.

**Comment by ugurdogrusoz** [comment]
How come Niki cannot open (menu is empty) these pathways in "Local" mode?

**Comment by ugurdogrusoz** [comment]
I suppose Niki no longer has this issue. Let's put the new PanCancer pathways provided by Konnor as samples as well. Let's organize these and TCGA pathways as follows:

Network > TCGA > (list of pathways we have currently)
Network > PanCancer > (this new list)

**Comment by ugurdogrusoz** [comment]
Please put Creighton one under PanCancer as well (as per Konnor). Also, for all these sample pathways, file name and title should be set properly (e.g. "PanCancer-Apoptosis-pathway.txt" and "PanCancer Apoptosis pathway", respectively).

**Comment by istemi-bahceci** [comment]
Fixed
