### ISSUE TITLE
Data synchronization problem in collaborative mode

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#66]
When in collaborative mode, if one user adds new alteration data (through Load from cBioPortal), this new data replaces any existing alteration data sets in other users' views (rather than appending the new ones to the end of the existing alteration data sets).

**Comment by istemi-bahceci** [comment]
This should be fixed now

**Comment by istemi-bahceci** [comment]
Updated unstable branch deployment ( http://www.pathwaymapper.org:3000/ )
