### ISSUE TITLE
Integration of node resize feature

### ISSUE THREAD

**Issue by istemi-bahceci** [iVis-at-Bilkent/pathway-mapper#67]
We should let users interactively resize nodes (using handles). We have an cytoscape.js extension for this purpose which we should integrate to pathway mapper ( https://github.com/iVis-at-Bilkent/cytoscape.js-node-resize )

**Comment by istemi-bahceci** [comment]
Seems that there is a conflict with dependencies, I will detect the problem and re-assign the issue back to you

**Comment by istemi-bahceci** [comment]
it seems that node resize requires ocanvas please try:

`npm install --save ocanvas`

**Comment by istemi-bahceci** [comment]
I've updated http://www.pathwaymapper.org:3000/ , probably it would be better if we could provide a UI for editing options of the extension under View > Resize Options, similar to "Grid Options"

**Comment by ugurdogrusoz** [comment]
What kind of options should we expose?

**Comment by ugurdogrusoz** [comment]
I don't think we need resize options.
The major problem here is that when a node is resized, it might be too small to show experiment data.

**Comment by ugurdogrusoz** [comment]
When you resize a node in collaborative mode, it shifts!

**Comment by ugurdogrusoz** [comment]
Can we also change grapple colors from orange to this: #ffc90e
