### ISSUE TITLE
Display Pubmed IDs for interactions as "Interaction Details" in the same way as "Gene Details" 

### ISSUE THREAD

**Issue by cannin** [iVis-at-Bilkent/pathway-mapper#71]
Could we have a details popup for interactions (non-editable)? The data would be a list of Pubmed IDs extracted from Pathway Commons. I could provide a list in whatever the format is necessary and/or try to commit code for this purpose if it is a reasonable idea.

**Comment by ugurdogrusoz** [comment]
@cannin after your earlier suggestion for showing such properties per interaction, we already did a little bit of investigation by asking @ozgunbabur. He says that some interactions (activates, inhibits) in PathwayMapper do not exist in PC, and others might not directly match/map. What do you think?

**Comment by cannin** [comment]
PC is a source of data, but the utility of having citations on interactions is independent of whether the interactions exist in PC. You can see the large effort around the current curation of these pathways. The potential for inconsistencies is why there should be means to manually curate the PMIDs that are shown rather than a completely automated pull from PC.

**Comment by ozgunbabur** [comment]
Yes I agree that the capability of manually associating literature references to the curated relations is a must have feature for a pathway curation tool.

**Comment by cannin** [comment]
An additional piece of information, if this gets implemented. 

For the sake of consistency, the PC SIFNX format has a semi-colon delimited list of PMIDs.

    AADAT	catalysis-precedes	DHTKD1	HumanCyc	12126930;23141293	

The user interface could allow this same format as input in the frontend and export the same.

**Comment by ugurdogrusoz** [comment]
For this, we decided for adding support to manually associate pubmed IDs with interactions.

**Comment by ugurdogrusoz** [comment]
Great! Just a couple of minor improvements:
- If input is not all digits (possibly separated by semicolon), ignore it (it appears as NaN at the moment)
- Capitalize dialog titles (both edge and node): Edge Details -> EDGE DETAILS, Node Details -> NODE DETAILS (if capitalization doesn't look good, use a bigger font instead)

**Comment by ugurdogrusoz** [comment]
@cannin please check and let us know if it works for you correctly
