### ISSUE TITLE
SIFNX Support? 

### ISSUE THREAD

**Issue by cannin** [iVis-at-Bilkent/pathway-mapper#74]
Could we have SIFNX support to allow better access to the output in Cytoscape and R? The current export is close. Below is how the export would change: 

Current

    New Pathway

    --NODE_NAME	NODE_ID	NODE_TYPE	PARENT_ID	POSX	POSY--
    CDK4	wyMGXBw8cUj6	GENE	-1	262	231	
    RB1	LrJe2ktmcVzK	GENE	-1	262	340	
    CDKN2A	N18olkvEcUJu	GENE	-1	387	127	
    TP53	-VLZ5keBcXa3	GENE	-1	488	340	
    MDM2	79evo3OUcVFA	GENE	-1	488	231	
    CCNE1	-le5m2j6cWa2	GENE	-1	80	340	

    --EDGE_ID	SOURCE	TARGET	EDGE_TYPE
    d3auWK_1cit5	79evo3OUcVFA	-VLZ5keBcXa3	INHIBITS
    w4Yp60k9chhi	N18olkvEcUJu	79evo3OUcVFA	INHIBITS
    XhRgnqAscgwV	N18olkvEcUJu	wyMGXBw8cUj6	INHIBITS
    0E_Xe1cUckq-	wyMGXBw8cUj6	LrJe2ktmcVzK	INHIBITS
    K9h1lRMzclc1	-le5m2j6cWa2	LrJe2ktmcVzK	INHIBITS

New

    --NODE_NAME	NODE_ID	NODE_TYPE	PARENT_ID	POSX	POSY PATHWAY--
    CDK4	wyMGXBw8cUj6	GENE	-1	262	231 New Pathway
    RB1	LrJe2ktmcVzK	GENE	-1	262	340 New Pathway
    CDKN2A	N18olkvEcUJu	GENE	-1	387	127 New Pathway
    TP53	-VLZ5keBcXa3	GENE	-1	488	340 New Pathway	
    MDM2	79evo3OUcVFA	GENE	-1	488	231 New Pathway	
    CCNE1	-le5m2j6cWa2	GENE	-1	80	340 New Pathway

    --EDGE_ID	SOURCE	TARGET	EDGE_TYPE
    d3auWK_1cit5	MDM2	TP53	INHIBITS
    w4Yp60k9chhi	CDKN2A	MDM2	INHIBITS
    XhRgnqAscgwV	CDKN2A	CDK4	INHIBITS
    0E_Xe1cUckq-	CDK4	RB1	INHIBITS
    K9h1lRMzclc1	CCNE1	RB1	INHIBITS

Maybe other little tweaks for standardization. Use the column names from Pathway Commons SIFNX, like PARTICIPANT_A in the edges. I'm also not sure how easy it is to sort columns. I left the above as is, but in SIF we would have SOURCE EDGE_TYPE TARGET.

**Comment by ugurdogrusoz** [comment]
For now, we decided to provide an export facility (Network > Export as > SIFNX; move what's under Network > Export as to Network > Export as > Image) for this.

**Comment by ugurdogrusoz** [comment]
Looks good. I notice we're missing tabs between certain column titles for interactions though:
PARTICIPANT_APARTICIPANT_BTYPE

**Comment by ugurdogrusoz** [comment]
@cannin Can you please check (Network > Export as > SIFNX) if the format is correct and let us know?

**Comment by ugurdogrusoz** [comment]
Please see https://github.com/iVis-at-Bilkent/pathway-mapper/pull/77

**Comment by ugurdogrusoz** [comment]
Closing this. @cannin let us know if there are further problems.
