### ISSUE TITLE
Limit number of data sets displayed

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#75]
The user should be able to upload any number of Alteration % data sets to overlay but at most 6 of them should be allowed to be displayed.

**Comment by ugurdogrusoz** [comment]
It'd be great a button that checks/unchecks all data sets in View Settings.

**Comment by ugurdogrusoz** [comment]
So looks like we limit display of only 3 upon load of a new alteration data. This is a constraint on top of that since if the current number of checked data sets go above 6 we display only 6 (first 6?)

**Comment by msalihaltun** [comment]
I forgot to link it but https://github.com/iVis-at-Bilkent/pathway-mapper/commit/ba700c24d738b0c0bfcca091219d29d8a78bc7bf handles this. I put warnings while loading studies and enabling more than six studies to be shown. 

The style is tentative, I think it's okay in terms of UX though. I also tried a more "scattered" style approach when laying out the "View Settings" modal.

**Comment by ugurdogrusoz** [comment]
Looks good, thanks. Some minor improvements are below.
In Load dialog:
- Make "Warning" bold in the warning text
- "different study data" -> "different data sets"
- "->" -> ">"
In Visibility settings warning dialog:
- "6 study data" -> "6 data sets"
- "some other study data" -> "some other data set"
