### ISSUE TITLE
Programmatic access of TCGA pathways in SIFNX

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#78]
As per Augustin's request, is there (can we provide) a way to programmatically access the TCGA pathways in SIFNX format?
Perhaps similar to accessing them in tab-delimited format using:
http://pathwaymapper.org/pathway?filename=GBM-2013-RTK-RAS-PI(3)K-pathway.txt

**Comment by istemi-bahceci** [comment]
Added SIFNX support to programmatic access. Example call: http://www.pathwaymapper.org/pathway?filename=GBM-2013-RTK-RAS-PI(3)K-pathway.txt&format=SIFNX

**Comment by ugurdogrusoz** [comment]
@cannin Please see if this is fine and close the issue if so!
