### ISSUE TITLE
Show 1 decimal place on alteration frequencies

### ISSUE THREAD

**Issue by cannin** [iVis-at-Bilkent/pathway-mapper#81]
Rounding is ok, but at 0% it may hide information of use. And it would be good to show 1 decimal place.

<img width="287" alt="screen shot 2017-03-17 at 12 21 18 pm" src="https://cloud.githubusercontent.com/assets/790284/24052636/94377c08-0b0c-11e7-9f04-9cc7a110e707.png">

**Comment by ugurdogrusoz** [comment]
Alternative is to display "<1%" as suggested by Niki when the value is in (0,1)
