### ISSUE TITLE
User control for color gradient

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#82]
The user should have better control for determining how the values map to white-{red,blue} color scale. For instance, some people might think 25% should map to full {red,blue}. One idea might be to let the user specify any number of colors with associated values, and determine the color of in between values using colors in between specified ones. Let's discuss.

**Comment by msalihaltun** [comment]
I just thought of this, but Collaborative needs to be aware of the current color selection as well.

**Comment by ugurdogrusoz** [comment]
Looks good for local use.
