### ISSUE TITLE
Grid guideline support enhancement

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#85]
Enhance the grid-guideline support by upgrading to the latest associated extension and adding two new tools in toolbar:
- Enable grid: Show and snap to grid
- Enable guidelines: Show and snap to geometric and distribution alignment guidelines

**Comment by ugurdogrusoz** [comment]
Make sure to update the expand-collapse extension to the latest

**Comment by istemi-bahceci** [comment]
Should be fixed

**Comment by ugurdogrusoz** [comment]
For guideline colors, let's simply go with what we have in Newt. Use #659bcd as color for all types of guidelines. Make distance guidelines solid (default) and geometric ones dashed.
