### ISSUE TITLE
Contact and credit information

### ISSUE THREAD

**Issue by cannin** [iVis-at-Bilkent/pathway-mapper#87]
Add contact information on the homepage?

**Comment by ugurdogrusoz** [comment]
We have contact info in Help > About but let's add add it to the homepage as well. Let's also add paper to cite (after the first line "Welcome to PathwayMapper", in smaller font size, centering all lines):
Please cite the following when using PathwayMapper: Bahceci et al. (2017) "PathwayMapper: a collaborative visual web editor for cancer pathways and genomic data", Bioinformatics.
ivis@cs.bilkent.edu.tr
https://github.com/iVis-at-Bilkent/pathway-mapper

**Comment by leonarddrv** [comment]
Is it ok like this, or should I make any change on Credit information?

**Comment by ugurdogrusoz** [comment]
Please update the hyperlink of the paper to:
https://academic.oup.com/bioinformatics/article/doi/10.1093/bioinformatics/btx149/3072875/PathwayMapper-a-collaborative-visual-web-editor

Also, let's change the font text color for email and web page to #979797

**Comment by ugurdogrusoz** [comment]
We are also missing: "Please cite the following when using "
