### ISSUE TITLE
Transfer bug

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#90]
- Create a family F
- Create a gene G in family F
- Create a compartment C
- Select BOTH G and F
- Right click C and choose "Add selected into this"; F & G are transferred into the compartment but G is no longer in F! This problem does not happen if only F is selected and transferred into C.

**Comment by MuluhGodson** [comment]
@ugurdogrusoz While creating G and assigning it to F, the G didn't move into F. But selecting both F and G to move into C works. Were you able to get G into F?

![image](https://user-images.githubusercontent.com/40151808/163173214-fc02e45d-5c60-49cb-8200-152a799b8145.png)

**Comment by ugurdogrusoz** [comment]
@MuluhGodson I am not sure what you mean. How is this related to the already reported bug?

**Comment by MuluhGodson** [comment]
> @MuluhGodson I am not sure what you mean. How is this related to the already reported bug?

my bad. I was having issues replicating the bug. I think I got it now.
