### ISSUE TITLE
Disable undo-redo in collaborative mode

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#98]
Since undo is not supported in collaborative mode, we should simply disable it (both menu and tool bar items) in that mode.

**Comment by ugurdogrusoz** [comment]
There should be a way to get rid of the extra padding on the right when undo/redo is not in the toolbar

**Comment by leonarddrv** [comment]
It was the lowest negative value that margin left property could take without affecting the other parts of toolbar.
