### ISSUE TITLE
Node style improvements

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/pathway-mapper#99]
Can we make our nodes more like the ones in the palette as follows:
- Gene and Complex borders are darker (black or very close to black)
- Family border is darker (same as current Gene/Complex border color)
- Compartment border is thicker (1.5 half times the current or so?)

**Comment by leonarddrv** [comment]
@ugurdogrusoz  I checked and it seems like Gene and Coplex border color is black (#000000).
I can make the family border darker, and I guess making compartment border 2 times the current seems like the one in the palette.
What should I do?

**Comment by ugurdogrusoz** [comment]
They dont look black though. Maybe the borders are too thin. Try making them a bit thicker inclunding family borders

**Comment by ugurdogrusoz** [comment]
perfect!
